version: '3'
services:
  backend:
    image: erasme/itineraires_fraicheur_backend:15-04-2024
    build: backend/
    env_file:
      - .env
    ports:
      - "3002:3002"
    #command: "tail -f /dev/null"
  frontend:
    image: erasme/itineraires_fraicheur_frontend:15-04-2024
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"