version: '3'
services:
  backend:
    build: backend/
    ports:
      - "3002:3002"
    env_file:
      - .env
    #command: "tail -f /dev/null"
  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"